---
title: "Pair-approximation model"
author: "Florian Schneider"
date: "Thursday, November 20, 2014"
output: html_document
runtime: shiny
---

   
## original model (Kéfi et al 2007)

Running the pair approximation model of Kéfi et al 2007 TPB dynamically. 


```{r, echo=FALSE}

library("deSolve")
model_parms <- list(
  delta = 0.1, # proportion of seeds dispersed globally
  b = 0.5, # environmental quality
  m = 0.05, # plant mortality
  f = 0.9, # effect of abiotic facilitation on regeneration
  r = 0.01, # intrinsic regeneration 
  d = 0.1, # rate of degradation
  c = 0.2 # global competition among plants 
  )

  setwd("C:/Users/SCHNEIDER/Documents/projects/CAS02_livestock")
  source("code/ode_kefi.r")

```

### plant and soil parameters
```{r, echo=FALSE}

inputPanel(
  sliderInput("b", label = "environmental quality:",
              min = 0.0, max = 1, value = 0.5, step = 0.01),
  sliderInput("m", label = "plant mortality:",
              min = 0.0, max = 1, value = 0.25, step = 0.01),
  sliderInput("c", label = "competition:",
              min = 0.0, max = 1, value = 0.2, step = 0.01),
  sliderInput("delta", label = "seed distpersal:",
              min = 0.0, max = 1, value = 0.1, step = 0.01),
  sliderInput("f", label = "facilitation:",
              min = 0.0, max = 1, value = 0.9, step = 0.01), 
  sliderInput("r", label = "regeneration rate:",
              min = 0.0, max = 1, value = 0.01, step = 0.01), 
  sliderInput("d", label = "degradation rate:",
              min = 0.0, max = 1, value = 0.1, step = 0.01)
)


```

### initial conditions
```{r, echo=FALSE}

inputPanel(
  sliderInput("rho_p", label = "initial plant cover:",
              min = 0.0, max = 1, value = 0.6, step = 0.01)
  )

renderPlot({


  model_parms$d <- as.numeric(input$d)
  model_parms$r <- as.numeric(input$r)
  model_parms$f <- as.numeric(input$f) 
  model_parms$b <- as.numeric(input$b) 
  model_parms$m <- as.numeric(input$m) 
  model_parms$c <- as.numeric(input$c) 
  model_parms$delta <- as.numeric(input$delta) 

  rho_ini <-as.numeric(input$rho_p)
rho <- c(rho_pm = rho_ini*0.4, # rho[1]
         rho_pp = rho_ini*0.4 , # rho[2]
         rho_mm = (1-rho_ini)*0.6, # rho[3]
         rho_p = rho_ini,  # rho[4]
         rho_m = (1-rho_ini)*0.9   # rho[5]
        )
  
  
runmodel <- ode(y = rho, func = odesys, times = 1.1^(1:60), parms = model_parms)

out <- as.data.frame(runmodel)
out$rho_0 <- 1 - out$rho_p - out$rho_m
out$rho_p0 <- with(out, rho_p-rho_pm-rho_pp)
out$rho_m0 <- with(out, rho_m-rho_pm-rho_mm)
out$rho_00 <- with(out, rho_0-rho_m0-rho_p0)

plot(rho_p ~ time, data = out, type = "l", lwd = 2, ylab = "rho_plus", main = "pair-approximation", ylim = c(0,1))
lines(rho_m ~ time, data = out, lty = 3)
lines(rho_0 ~ time, data = out, col = "grey50")
  

} )
```
